### ISSUE TITLE
IntelliJ freezes with version 2022.x of the plugin

### ISSUE THREAD

**Issue by rvankraaij** [aemide/issues#149]
Noticed that after installing the 2022.x version of the plugin IntelliJ hangs after some time and several freeze thread dumps are written to disk. I've attached one of them.

[threadDump-20220422-140812.txt](https://github.com/aemide/issues/files/8540880/threadDump-20220422-140812.txt)

I'm running IntelliJ version 2022.1

No issues with version 2021.1.3 of the plugin

**Comment by karollewandowski** [comment]
Hi @rvankraaij, thank you very much for the report.

Is there any chance that you provide us with all the created thread dumps? It is hard to get conclusions from the single one. One stacktrace includes the AEM IDE code, but I'm not sure it is significant. Do you have in your project any symbolic links pointing to directories?

**Comment by karollewandowski** [comment]
Thanks for detailed information, it helped to solve the issue.

The issue fix is implemented and will be released in 2022.2.1.

If you would like to use it earlier, it is possible to use EAP releases channel. To get EAP updates, configure your IDE according to the instructions (using "eap" channel name):
https://plugins.jetbrains.com/docs/marketplace/custom-release-channels.html#configuring-a-custom-channel-in-intellij-platform-based-ides

We release EAP versions more frequently than stable versions and this fix should be released today in ~2-3h.
