### ISSUE TITLE
Bug: Options for After Pull get swapped after restart

### ISSUE THREAD

**Issue by HitmanInWis** [aemide/issues#855]
On Languages & Frameworks -> AEM -> Content Sync -> Pulling I am set up as:

(x) Clean up content files
( ) Reformat content files

However, after I restart the IDE, the enabled option gets swapped to:

( ) Clean up content files
(x) Reformat content files

This requires me to remember to fix the setting every time I open the IDE.

**Comment by karollewandowski** [comment]
Hi Brett,
Thanks a lot for reporting this. It is fixed and will be available in the next version (we aim to release it this or the following week).
